static const char *html_form = 
"<html>"
"<head><title>S7FW Client</title></head>"
"<body>"
"<form method=\"POST\" name=\"form1\">"
"Type: <select name=\"input_type\">"
"<option value=\"ALL\">ALL</option>"
"<option value=\"TCP\">TCP</option>"
"<option value=\"UDP\">UDP</option>"
"<option value=\"IP\">IP</option>"
"<option value=\"ARP\">ARP</option>"
"<option value=\"RARP\">RARP</option>"
"<option value=\"OTHER\">OTHER</option></select>"
"Port: <input type=\"text\" name=\"input_port\" />"
"Operation:<select name=\"input_op\">"
"<option value=\"Denied\">Denied</option>"
"<option value=\"Pass\">Pass</option></select><br/>"
"<input type=\"button\" value=\"Search Log\" onclick=\"form1.action='/log';form1.submit();\"/>"
"<input type=\"button\" value=\"Add Rule\" onclick=\"form1.action='/rule';form1.submit();\"/></form>"
"</body>"
"</html>";