static const char *html_form = 
"<html><head><title>S7FW Client</title><script>"
"function check_IP(){"
	"var src_ip=document.getElementsByName('input_src_ip')[0].value;"
	"var dst_ip=document.getElementsByName('input_dst_ip')[0].value;"
	"var src_pass=false;"
	"var dst_pass=false;"
	"if(src_ip=='' && dst_ip=='')"
		"return true;"
	"var re=/^(\\d+)\\.(\\d+)\\.(\\d+)\\.(\\d+)$/;"
	"if(re.test(src_ip)){"
		"if(RegExp.$1<256 && RegExp.$2<256 && RegExp.$3<256 && RegExp.$4<256)"
			"src_pass=true;"
	"}"
	"if(re.test(dst_ip)){"
		"if(RegExp.$1<256 && RegExp.$2<256 && RegExp.$3<256 && RegExp.$4<256)"
			"dst_pass=true;"
	"}"
	"if(src_pass && dst_pass)"
		"return true;"
	"else{"
		"alert('Invalid IP!');"
		"return false;"
	"}"
"}"
"function check_Status(){"
	"var st=document.getElementsByName('input_op')[0].value;"
	"if(st=='ALL'){"
		"alert('Must specify an operation when Add Rule, can not be ALL');"
		"return false;"
	"}"
	"return true;"
"}"
"function check_Port(){"
	"var s_port=document.getElementsByName('input_src_port')[0].value;"
	"var d_port=document.getElementsByName('input_dst_port')[0].value;"
	"if((s_port!=''&&isNaN(s_port))||(d_port!=''&&isNaN(d_port))){"
		"alert('Invalid Port!');"
		"return false;"
	"}"
	"if((s_port!=''&&(s_port<0||s_port>65535))||(d_port!=''&&(d_port<0||d_port>65535))){"
		"alert('Invalid Port!');"
		"return false;"
	"}"
	"return true;"
"}"
"</script></head><body>"
"<form method=\"POST\" name=\"form1\">"
"Type: <select name=\"input_type\">"
"<option value=\"ALL\">ALL</option>"
"<option value=\"TCP\">TCP</option>"
"<option value=\"UDP\">UDP</option>"
"<option value=\"IP\">IP</option>"
"<option value=\"ARP\">ARP</option>"
"<option value=\"RARP\">RARP</option>"
"<option value=\"OTHER\">OTHER</option></select><br/>"
"Src IP: <input type=\"text\" name=\"input_src_ip\" />"
"Src Port: <input type=\"text\" name=\"input_src_port\" /><br/>"
"Dst IP: <input type=\"text\" name=\"input_dst_ip\" />"
"Dst Port: <input type=\"text\" name=\"input_dst_port\" /><br/>"
"Operation:<select name=\"input_op\">"
"<option value=\"ALL\">ALL</option>"
"<option value=\"Denied\">Denied</option>"
"<option value=\"Pass\">Pass</option></select><br/>"
"<input type=\"button\" value=\"Search Log\" onclick=\"form1.action='/log';if(check_IP()&&check_Port())form1.submit();\"/>"
"<input type=\"button\" value=\"Add Rule\" onclick=\"form1.action='/rule';if(check_IP()&&check_Status()&&check_Port())form1.submit();\"/></form>"
"</body>"
"</html>";