
static const char *html_form = 
"<html><head><title>S7FW Client</title>"
"<script src=\"jquery.min.js\"></script>"
"<script src=\"json2.min.js\"></script>"
"<script>"
"function check_IP(){"
	"var src_ip=document.getElementsByName('input_src_ip')[0].value;"
	"var dst_ip=document.getElementsByName('input_dst_ip')[0].value;"
	"var src_pass=false;"
	"var dst_pass=false;"
	"if(src_ip=='')"
		"src_pass=true;"
	"if(dst_ip=='')"
		"dst_pass=true;"
	"var re=/^(\\d+)\\.(\\d+)\\.(\\d+)\\.(\\d+)$/;"
	"if(re.test(src_ip)){"
		"if(RegExp.$1<256 && RegExp.$2<256 && RegExp.$3<256 && RegExp.$4<256)"
			"src_pass=true;"
	"}"
	"if(re.test(dst_ip)){"
		"if(RegExp.$1<256 && RegExp.$2<256 && RegExp.$3<256 && RegExp.$4<256)"
			"dst_pass=true;"
	"}"
	"if(src_pass && dst_pass)"
		"return true;"
	"else{"
		"alert('Invalid IP!');"
		"return false;"
	"}"
"}"
"function check_Status(){"
	"var st=document.getElementsByName('input_op')[0].value;"
	"if(st=='ALL'){"
		"alert('Must specify an operation when Add Rule, can not be ALL');"
		"return false;"
	"}"
	"return true;"
"}"
"function check_Port(){"
	"var s_port=document.getElementsByName('input_src_port')[0].value;"
	"var d_port=document.getElementsByName('input_dst_port')[0].value;"
	"if((s_port!=''&&isNaN(s_port))||(d_port!=''&&isNaN(d_port))){"
		"alert('Invalid Port!');"
		"return false;"
	"}"
	"if((s_port!=''&&(s_port<0||s_port>65535))||(d_port!=''&&(d_port<0||d_port>65535))){"
		"alert('Invalid Port!');"
		"return false;"
	"}"
	"return true;"
"}"
"$.fn.serializeObject = function(){"
	"var o={};var a=this.serializeArray();"
	"$.each(a,function(){"
		"if (o[this.name]!==undefined){"
			"if (!o[this.name].push){"
				"o[this.name]=[o[this.name]];"
			"}"
			"o[this.name].push(this.value||'');"
		"}else{"
			"o[this.name]=this.value||'';"
		"}"
	"});"
	"return o;"
"};"
"function Submit(action,type){"
	"if (check_IP()&&check_Port()){"
		"$(\"input[name='input_name']\").val(Math.random().toString(36).substr(12));"
		"if (type==1){"
			"$(\"input[name='input_manage']\").val('ADD');"
			"if (!check_Status())"
				"return;"
		"}"
		"else if (type==2)"
		"{"
			"if ($(\"input[name='input_index']\").val().length==0)"
			"{"
				"alert('Must specify Rule No when remove rule.');"
				"return;"
			"}"
			"$(\"input[name='input_manage']\").val('REMOVE');"
		"}"	
		"var obj=$('#s7m').serializeObject();"
		"var data='{\"entrys\":['+JSON.stringify(obj)+']}';"
		"$(\"#content\").html('working...');"
		"$.post(action,data,function(result){"
			"$(\"#content\").html(result);"
		"});"
	"}"
"}"
"function Reg(){"
	"location.href='/admin';"
"}"
"</script></head><body>"
"<center>"
"<form method=\"POST\" name=\"mform\" id=\"s7m\">"
"Src IP: <input type=\"text\" name=\"input_src_ip\" />"
"Src Port: <input type=\"text\" name=\"input_src_port\" /><br/>"
"Dst IP: <input type=\"text\" name=\"input_dst_ip\" />"
"Dst Port: <input type=\"text\" name=\"input_dst_port\" /><br/>"
"Type: <select name=\"input_type\">"
"<option value=\"ALL\">ALL</option>"
"<option value=\"TCP\">TCP</option>"
"<option value=\"UDP\">UDP</option>"
"<option value=\"IP\">IP</option>"
"<option value=\"ARP\">ARP</option>"
"<option value=\"RARP\">RARP</option>"
"<option value=\"OTHER\">OTHER</option></select>"
"Operation:<select name=\"input_op\">"
"<option value=\"ALL\">ALL</option>"
"<option value=\"Denied\">Denied</option>"
"<option value=\"Warning\">Warning</option>"
"<option value=\"Pass\">Pass</option></select>"
"Rule No.:<input type=\"text\" name=\"input_index\" /><br/>"
"DATA:<input type=\"text\" name=\"input_data_pi\" />"
"POSITION:<input type=\"text\" name=\"input_data_pos\" />"
"LENGTH:<input type=\"text\" name=\"input_data_len\" /><br/>"
"<input type=\"button\" value=\"Search Log\" onclick=\"Submit('/log')\"/>"
"<input type=\"button\" value=\"Add Rule\" onclick=\"Submit('/rule',1)\"/>"
"<input type=\"button\" value=\"Remove Rule\" onclick=\"Submit('/rule',2)\"/>"
"<input type=\"hidden\" name=\"input_manage\" value=\"ADD\" />"
"<input type=\"hidden\" name=\"input_name\" />"
"<input type=\"button\" value=\"Register\" onclick=\"Reg()\" /></form>"
"<hr/><div id=\"content\"></div></center>"
"</body>"
"</html>";

static const char *server_form = 
"<html><head><title>Server Config</title>"
"<script>"
"function check_IP()"
"{"
	"var ip=document.getElementsByName('input_server_ip')[0].value;"
	"if(ip=='')"
	"{"
		"alert('Server IP Can not be NULL');"
		"return false;"
	"}"
	"var re=/^(\\d+)\\.(\\d+)\\.(\\d+)\\.(\\d+)$/;"
	"if(re.test(ip)){"
	"if(RegExp.$1<256 && RegExp.$2<256 && RegExp.$3<256 && RegExp.$4<256)"
		"return true;"
	"}"
	"alert('Invalid IP');"
	"return false;"
"}"
"function Submit()"
"{"
	
	"if (!check_IP())"
	"{"
		"return;"
	"}"
	"var my_name=document.getElementsByName('input_my_name')[0].value;"
	"var status=document.getElementsByName('input_status')[0].value;"
	"var ip=document.getElementsByName('input_server_ip')[0].value;"
	"if (my_name=='')"
		"my_name = Math.random().toString(36).substr(8);"
	"var xmlhttp=new XMLHttpRequest();"
	"xmlhttp.onreadystatechange=function()"
	"{"
		"if (xmlhttp.readyState==4 && xmlhttp.status==200)"
		"{"
			"document.getElementById(\"content\").innerHTML=xmlhttp.responseText;"
		"}"
	"};"
	"xmlhttp.open(\"POST\",\"/admin\",true);"
	"xmlhttp.send('input_my_name='+my_name+'&input_server_ip='+ip+'&input_status='+status);"
"}"
"</script>"
"</head>"
"<body>"
"<form method=\"POST\" name=\"cform\" id=\"s7c\">"
"My Name: <input type=\"text\" name=\"input_my_name\" /><br />"
"Server IP: <input type=\"text\" name=\"input_server_ip\" /><br />"
"<input type=\"button\" value=\"Register\" onclick=\"Submit()\" /><br />"
"<input type=\"hidden\" name=\"input_status\" value=\"online\" />"
"</form>"
"<hr/><div id=\"content\"></div>"
"</body>"
"</html>";